### ISSUE TITLE
[BUG] Connection error: websocket error

### ISSUE THREAD

**Issue by canuckbrian** [rcourtman/pulse#1]
## Bug Description
After following the Docker Compose installation instructions, access to the Pulse web interface is not possible due to a "websocket error".

## Steps To Reproduce
1. Follow instructions from GitHub to download the docker-compose.yml and .env file
2. Customize .env file with PVE node API token and details
3. Start container using docker compose
4. Access web UI directly by IP:Port

## Expected Behavior
Pulse dashboard loads

## Actual Behavior
Page loads but contains an error message: "Connection error: websocket error"

## Screenshots

![Image](https://github.com/user-attachments/assets/7ce53671-0988-41c3-ba42-e3d6772d212b)

## Environment
- OS: Ubuntu 24.04.2
- Browser: Chrome 134
- ProxMox Version: 8.3.4
- Pulse Version: 1.3.0
- Deployment Method: Docker Compose
- Docker Version: 28.0.1, build 068a01e

## Additional Context
**LAN Subnet:** 192.168.10.0/24
**Docker Server IP:** 192.168.10.3
**PVE-001 Node IP:** 192.168.10.51
**PVE-002 Node IP:** 192.168.10.52

**.env File:**
```
# ProxMox Node Configuration
# Replace with your ProxMox node details

# Node 1
PROXMOX_NODE_1_NAME=PVE-001
PROXMOX_NODE_1_HOST=https://pve-001.home.local:8006
PROXMOX_NODE_1_TOKEN_ID=root@pam!pulse
PROXMOX_NODE_1_TOKEN_SECRET=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx

# Node 2
PROXMOX_NODE_2_NAME=PVE-002
PROXMOX_NODE_2_HOST=https://pve-002.home.local:8006
PROXMOX_NODE_2_TOKEN_ID=root@pam!pulse
PROXMOX_NODE_2_TOKEN_SECRET=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx

# App Configuration
PORT=7654

# Frontend Configuration
# This ensures the frontend connects to the backend using IPv4 instead of IPv6
# Important: Use 127.0.0.1 (IPv4) instead of ::1 (IPv6) to avoid connection issues
#VITE_API_URL=http://127.0.0.1:7654
VITE_API_URL=http://192.168.10.3:7654

# Environment Configuration
# Note: When using start-dev.sh for development, it will automatically set NODE_ENV=development
# These settings primarily apply to Docker/production deployments
NODE_ENV=production
LOG_LEVEL=info  # Options: error, warn, info, debug
ENABLE_DEV_TOOLS=false  # Set to true only for debugging production issues
METRICS_HISTORY_MINUTES=60  # How many minutes of metrics history to keep in memory

# Mock Data Configuration
# Set to false to connect to real Proxmox nodes
USE_MOCK_DATA=false
MOCK_DATA_ENABLED=false

# SSL Configuration
# SECURITY WARNING:
# - For development or internal networks, you can set these to true/0
# - For production, set these to false/1 and ensure proper SSL certificates are installed
# - Setting these to true/0 disables SSL certificate validation and is not secure for production
IGNORE_SSL_ERRORS=true
NODE_TLS_REJECT_UNAUTHORIZED=0

# Polling Intervals (in milliseconds)
NODE_POLLING_INTERVAL_MS=1000
EVENT_POLLING_INTERVAL_MS=1000
```

**Docker Compose Log Output:**
```
root@docker:/var/docker/pulse# docker compose up -d && docker compose logs -f
[+] Running 2/2
 ✔ Network pulse_default  Created                                                                                                                               0.1s
 ✔ Container pulse-app    Started                                                                                                                               0.3s
pulse-app  | 2025-03-09 21:39:06 info [NodeManager]: Initializing NodeManager
pulse-app  | 2025-03-09 21:39:06 info [NodeManager]: Adding node: PVE-002 (https://pve-002.home.local:8006)
pulse-app  | 2025-03-09 21:39:06 info [ProxmoxClient][node-2]: ProxMox API client created with timeout: 60000ms and 3 retry attempts
pulse-app  | 2025-03-09 21:39:06 info [MetricsService]: Metrics history configured for 60 minutes (120 data points)
pulse-app  | 2025-03-09 21:39:06 info [WebSocketServer]: WebSocket server initialized with multiple socket connections
pulse-app  | 2025-03-09 21:39:06 info [Server]: Server started on port 7654 in production mode
pulse-app  | 2025-03-09 21:39:06 info [Server]: Access the application at http://[your-server-ip]:7654
pulse-app  | 2025-03-09 21:39:06 info [ProxmoxClient][node-2]: Discovered node name by status check: pve-002
pulse-app  | 2025-03-09 21:39:06 info [ProxmoxClient][node-2]: Connection test successful
pulse-app  | 2025-03-09 21:39:06 info [ProxmoxClient][node-2]: Setting up event polling with base interval: 1000ms
pulse-app  | 2025-03-09 21:39:06 info [NodeManager]: Node added successfully: PVE-002
pulse-app  | 2025-03-09 21:39:06 info [NodeManager]: Adding node: PVE-001 (https://pve-001.home.local:8006)
pulse-app  | 2025-03-09 21:39:06 info [ProxmoxClient][node-1]: ProxMox API client created with timeout: 60000ms and 3 retry attempts
pulse-app  | 2025-03-09 21:39:06 info [ProxmoxClient][node-1]: Discovered node name by status check: pve-003
pulse-app  | 2025-03-09 21:39:06 info [ProxmoxClient][node-1]: Connection test successful
pulse-app  | 2025-03-09 21:39:06 info [ProxmoxClient][node-1]: Setting up event polling with base interval: 1000ms
pulse-app  | 2025-03-09 21:39:06 info [NodeManager]: Node added successfully: PVE-001
pulse-app  | 2025-03-09 21:39:06 info [NodeManager]: Starting polling for node updates (interval: 1000ms)
```

I have obfuscated all API tokens and hostnames for security / privacy reasons.

**Comment by Anexgohan** [comment]
Same issue as OP, although im using the API token called 'monitor-token' with a user called 'monitor' instead of root, rest all default
My compose is running in an lxc container with Docker

PROXMOX_NODE_1_NAME=pve-name
PROXMOX_NODE_1_HOST=http://192.168.xxx.xxx:8006
PROXMOX_NODE_1_TOKEN_ID=monitor@pam!monitor-token
PROXMOX_NODE_1_TOKEN_SECRET=<xxxxx>-<xxxxx>-<xxxxx>-<xxxxx>-<xxxxx>

![Image](https://github.com/user-attachments/assets/75113014-ff93-479f-b42b-bb77018d0da6)

**Comment by Tukamok** [comment]
I'm here with a "Me too" as well.  My environment isn't substantially different than OPs.

I've turned debug logging on, and it does show that it is polling and receiving data from my PVE cluster.  So I'm assuming this is simply an issue with the front and back ends not successfully talking to each other.

**Comment by Tukamok** [comment]
one additional thing I've noticed is that when I look at what's going on in DevTools/Network I see the call to ws://127.0.0.01:7654 even though I've set VITE_API_URL to be the local IP

**Comment by oezh** [comment]
Same error here. Config is the same as OP.

**Comment by garrettstoupe** [comment]
Also having the same error on Pulse

**Comment by PatrickTerlisten** [comment]
Same issue.  Dedicated user with PVEAuditor role, API permission assigned to /.

```
Invalid log level: info  # Options: error, warn, info, debug. Using 'info' as default.
2025-03-10 07:47:42 info [NodeManager]: Initializing NodeManager
2025-03-10 07:47:42 info [NodeManager]: Adding node: pve (https://pve.mlnetwork.local:8006)
2025-03-10 07:47:42 info [ProxmoxClient][node-1]: ProxMox API client created with timeout: 60000ms and 3 retry attempts
2025-03-10 07:47:42 info [MetricsService]: Metrics history configured for 60 minutes (120 data points)
2025-03-10 07:47:42 info [WebSocketServer]: WebSocket server initialized with multiple socket connections
2025-03-10 07:47:42 info [Server]: Server started on port 7654 in production mode
2025-03-10 07:47:42 info [Server]: Access the application at http://[your-server-ip]:7654
(node:6) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `node --trace-warnings ...` to show where the warning was created)
2025-03-10 07:47:42 error [ProxmoxClient][node-1]: API Error: 403 GET /nodes/pve/status
{
  "data": {
    "message": "Permission check failed (/nodes/pve, Sys.Audit)\n",
    "data": null
  }
}
2025-03-10 07:47:42 error [ProxmoxClient][node-1]: API Error: 403 GET /nodes/pve/status
{
  "data": {
    "data": null,
    "message": "Permission check failed (/nodes/pve, Sys.Audit)\n"
  }
}
2025-03-10 07:47:42 error [ProxmoxClient][node-1]: Connection test failed
{
  "error": {
    "message": "Request failed with status code 403",
    "name": "AxiosError",
    "code": "ERR_BAD_REQUEST"
  }
}
2025-03-10 07:47:42 error [NodeManager]: Failed to connect to node: pve
2025-03-10 07:47:42 info [NodeManager]: Starting polling for node updates (interval: 1000ms)
```

**Comment by vgeorgiev69** [comment]
> Same issue. Dedicated user with PVEAuditor role, API permission assigned to /.
> 
> ```
> Invalid log level: info  # Options: error, warn, info, debug. Using 'info' as default.
> 2025-03-10 07:47:42 info [NodeManager]: Initializing NodeManager
> 2025-03-10 07:47:42 info [NodeManager]: Adding node: pve (https://pve.mlnetwork.local:8006)
> 2025-03-10 07:47:42 info [ProxmoxClient][node-1]: ProxMox API client created with timeout: 60000ms and 3 retry attempts
> 2025-03-10 07:47:42 info [MetricsService]: Metrics history configured for 60 minutes (120 data points)
> 2025-03-10 07:47:42 info [WebSocketServer]: WebSocket server initialized with multiple socket connections
> 2025-03-10 07:47:42 info [Server]: Server started on port 7654 in production mode
> 2025-03-10 07:47:42 info [Server]: Access the application at http://[your-server-ip]:7654
> (node:6) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
> (Use `node --trace-warnings ...` to show where the warning was created)
> 2025-03-10 07:47:42 error [ProxmoxClient][node-1]: API Error: 403 GET /nodes/pve/status
> {
>   "data": {
>     "message": "Permission check failed (/nodes/pve, Sys.Audit)\n",
>     "data": null
>   }
> }
> 2025-03-10 07:47:42 error [ProxmoxClient][node-1]: API Error: 403 GET /nodes/pve/status
> {
>   "data": {
>     "data": null,
>     "message": "Permission check failed (/nodes/pve, Sys.Audit)\n"
>   }
> }
> 2025-03-10 07:47:42 error [ProxmoxClient][node-1]: Connection test failed
> {
>   "error": {
>     "message": "Request failed with status code 403",
>     "name": "AxiosError",
>     "code": "ERR_BAD_REQUEST"
>   }
> }
> 2025-03-10 07:47:42 error [NodeManager]: Failed to connect to node: pve
> 2025-03-10 07:47:42 info [NodeManager]: Starting polling for node updates (interval: 1000ms)
> ```

This is solved by putting the secret in double quotes, I had the same issue. (e.g. "my-token-id"

Apart from that, I'm still getting a connection timeout error. I tried running it in normal docker, alpine docker, LXC container - same results. I don't have logs indicating there's an error.

My current logs are:


`2025-03-10 09:29:47 info [ProxmoxClient][node-1]: Discovered node name by status check: proxmox

2025-03-10 09:29:47 info [ProxmoxClient][node-1]: Connection test successful

2025-03-10 09:29:47 info [ProxmoxClient][node-1]: Setting up event polling with base interval: 1000ms

2025-03-10 09:29:47 info [NodeManager]: Node added successfully: Proxmox Node 1

2025-03-10 09:29:47 info [NodeManager]: Starting polling for node updates (interval: 1000ms)`

**Comment by rcourtman** [comment]
# Fixing WebSocket Connection Issues in Pulse

Hey! I've seen a few people run into this WebSocket connection error, particularly when running Pulse through Docker. Let me help you get this sorted out.

## What's Going On?

When you see the error message:
```
Connection error: websocket error
```
it usually means the frontend can't establish a real-time connection with the backend. The page loads, but the live updates aren't working.

I've found this typically happens for a few reasons:
1. The way your reverse proxy is handling WebSocket connections
2. Some manual configuration in the `.env` file that's getting in the way
3. Network stuff blocking the WebSocket traffic
4. Docker networking not playing nice with the WebSocket connection

## Let's Fix It!

### First Try: The Simple Fix

Remove the `VITE_API_URL` from your `.env` file if you've got it set. Pulse is actually designed to handle this automatically, and sometimes manually setting this can cause issues.

### Second Try: Update Your Docker Setup

Here's a `docker-compose.yml` that I know works well:

```yaml
services:
  pulse-app:
    image: rcourtman/pulse:1.3.1
    container_name: pulse-app
    ports:
      - "7654:7654"
    environment:
      - NODE_ENV=production
      - PROXMOX_NODE_1_NAME=PVE-001
      - PROXMOX_NODE_1_HOST=https://pve-001.home.local:8006
      - PROXMOX_NODE_1_TOKEN_ID=root@pam!pulse
      - PROXMOX_NODE_1_TOKEN_SECRET=your-token-secret
      # Add your second node if you have one
      - PROXMOX_NODE_2_NAME=PVE-002
      - PROXMOX_NODE_2_HOST=https://pve-002.home.local:8006
      - PROXMOX_NODE_2_TOKEN_ID=root@pam!pulse
      - PROXMOX_NODE_2_TOKEN_SECRET=your-token-secret
      - IGNORE_SSL_ERRORS=true
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    restart: unless-stopped
```

### Third Try: Check Your Reverse Proxy

If you're using a reverse proxy (like nginx or Apache), this is often the culprit. Here's how to fix it:

#### For Nginx Users
Add this to your nginx config:
```nginx
location /socket.io {
    proxy_pass http://your-pulse-server:7654;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $host;
}

location / {
    proxy_pass http://your-pulse-server:7654;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
}
```

#### For Apache Users
Add this to your Apache config:
```apache
RewriteEngine On
RewriteCond %{REQUEST_URI}  ^/socket.io            [NC]
RewriteCond %{QUERY_STRING} transport=websocket    [NC]
RewriteRule /(.*)           ws://your-pulse-server:7654/$1 [P,L]

ProxyPass / http://your-pulse-server:7654/
ProxyPassReverse / http://your-pulse-server:7654/
```

### Fourth Try: Network Stuff

If you're still having issues, check these things:
1. Make sure port 7654 is open for both TCP and WebSocket traffic
2. Check your firewalls aren't blocking WebSocket connections
3. If you're using Kubernetes or something similar, verify the service config allows WebSocket traffic

## How to Check If It's Working

The easiest way to check if the WebSocket connection is working:
1. Open your browser's Dev Tools (F12)
2. Click on the Network tab
3. Filter for "WS" or "WebSocket"
4. Load up Pulse
5. You should see a connection to `/socket.io` that stays open

## Common Errors I've Seen

If you're getting:
- **WebSocket connection failed**: Usually means the port isn't accessible or something's blocking it
- **Connection timed out**: Check your network connection and make sure the backend is running
- **Invalid WebSocket frame**: This often pops up when the reverse proxy config isn't quite right

## Still Not Working?

Let me know what you see in:
1. Your browser's console (F12 > Console tab)
2. The Docker logs:
   ```bash
   docker logs pulse-app
   ```
3. Try connecting directly with:
   ```bash
   websocat ws://your-server:7654/socket.io
   ```

**Comment by kbekus** [comment]
Same issue as the original poster.  Using the developer console in Chrome I'm seeing attempts to connect to ws://127.0.0.1:7654 even though I have the environmental variable set as VITE_API_URL=http://192.168.2.82:7654

I've tried commenting out the VITE_API_URL env, I've tried it as 127.0.0.1 and I've tried it as the actual host IP. Same result.

**Comment by vgeorgiev69** [comment]
Same issue as above, tried what you suggested with both the 1.3.1 and 1.4.1 - the websocket goes to 127.0.0.1 with NS_ERR_CONNECTION_REFUSED

**Comment by casperleenheer** [comment]
Running with logs in debug. Running with docker-compose like this:

```
services:
  pulse-app:
    image: rcourtman/pulse:latest
    container_name: pulse-app
    ports:
      - 7654:7654
    #env_file:

    environment:
      - LOG_LEVEL=debug
      - NODE_OPTIONS=--no-warnings
      - SUPPRESS_NO_CONFIG_WARNING=true
      - IGNORE_SSL_ERRORS=true
      - NODE_TLS_REJECT_UNAUTHORIZED=0
      - PROXMOX_NODE_1_NAME=pve
      - PROXMOX_NODE_1_HOST=https://pve:8006
      - PROXMOX_NODE_1_TOKEN_ID=root@pam!pulse
      - PROXMOX_NODE_1_TOKEN_SECRET=xyz
      - NODE_ENV=production
      - VITE_API_URL=http://192.168.3.123:7654
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: "1"
    restart: unless-stopped
networks: {}

```
So reading the data is ok.

```
2025-03-10 12:47:22 debug [ProxmoxClient][node-1]: Raw resource data for container 108:
pulse-app  | {
pulse-app  |   "resourceData": {
pulse-app  |     "diskwrite": 0,
pulse-app  |     "type": "lxc",
pulse-app  |     "swap": 0,
pulse-app  |     "uptime": 492992,
pulse-app  |     "vmid": 108,
pulse-app  |     "cpu": 0,
pulse-app  |     "tags": "community-script;network;vpn",
pulse-app  |     "ha": {
pulse-app  |       "managed": 0
pulse-app  |     },
pulse-app  |     "mem": 62320640,
pulse-app  |     "maxmem": 536870912,
pulse-app  |     "maxdisk": 4294967296,
pulse-app  |     "diskread": 151719936,
pulse-app  |     "netin": 450629671,
pulse-app  |     "pid": 6458,
pulse-app  |     "cpus": 1,
pulse-app  |     "disk": 1545338880,
pulse-app  |     "status": "running",
pulse-app  |     "maxswap": 536870912,
pulse-app  |     "netout": 28304,
pulse-app  |     "name": "wireguard"
pulse-app  |   }
pulse-app  | }
```

But after a while I get:

```
 2025-03-10 12:49:39 error [ProxmoxClient][node-1]: API Error: getaddrinfo EAI_AGAIN pve
pulse-app  | {
pulse-app  |   "error": {
pulse-app  |     "message": "getaddrinfo EAI_AGAIN pve",
pulse-app  |     "name": "Error",
pulse-app  |     "code": "EAI_AGAIN"
pulse-app  |   }
pulse-app  | }
pulse-app  | 2025-03-10 12:49:39 warn [ProxmoxClient][node-1]: Retrying request (attempt 2/3): GET /nodes/pve/lxc/108/status/current
pulse-app  | 2025-03-10 12:49:39 debug [ProxmoxClient][node-1]: API Request: GET /nodes/pve/lxc/108/status/current
pulse-app  | {}
pulse-app  | 2025-03-10 12:49:39 error [ProxmoxClient][node-1]: API Error: getaddrinfo EAI_AGAIN pve
pulse-app  | {
pulse-app  |   "error": {
pulse-app  |     "message": "getaddrinfo EAI_AGAIN pve",
pulse-app  |     "name": "Error",
pulse-app  |     "code": "EAI_AGAIN"
pulse-app  |   }
pulse-app  | }
```

The server is a Intel I7 with 20 cores. Maybe it's hitting Proxmox to heavy? I also get outage warnings on my services (from other monitoring software) which automatically recover when I stop pulse. Messages like this: [plex] [🔴 Down] getaddrinfo ENOTFOUND plex.

**Comment by rcourtman** [comment]
Hey everyone, I see several of you are still experiencing this WebSocket connection issue. Let me try to help:

The key is to make sure the frontend can properly connect to the backend WebSocket server:

1. **Remove the VITE_API_URL line completely from your .env file** - this is causing more problems than it solves.

2. For Docker users, try this simplified docker-compose.yml:
```yaml
services:
  pulse-app:
    image: rcourtman/pulse:latest
    container_name: pulse-app
    ports:
      - "7654:7654"
    environment:
      - NODE_ENV=production
      - PROXMOX_NODE_1_NAME=your-node-name
      - PROXMOX_NODE_1_HOST=https://your-proxmox-host:8006
      - PROXMOX_NODE_1_TOKEN_ID=your-token-id
      - PROXMOX_NODE_1_TOKEN_SECRET=your-token-secret
      - IGNORE_SSL_ERRORS=true
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    restart: unless-stopped
```

3. If you're still having issues, try accessing the app directly by IP:port without any reverse proxy first. This will help isolate if it's a Docker networking issue or a reverse proxy configuration problem.

4. For those seeing `NS_ERR_CONNECTION_REFUSED` errors, check that:
   - Port 7654 is open on your firewall
   - You're accessing the app from the same network (or port forwarding is set up correctly)
   - Try using Docker's host network mode: add `network_mode: "host"` to your docker-compose.yml

I'm working on a new version that will improve the WebSocket connection handling and provide better error messages. I'll release it soon, but in the meantime, please try these workarounds and let me know if they help.

**Comment by casperleenheer** [comment]
I now have this as docker-compose

```
services:
  pulse-app:
    image: rcourtman/pulse:latest
    container_name: pulse-app
    ports:
      - 7654:7654
    #env_file:

    environment:
      - NODE_ENV=production
      - PROXMOX_NODE_1_NAME=pve
      - PROXMOX_NODE_1_HOST=https://pve:8006
      - PROXMOX_NODE_1_TOKEN_ID=root@pam!pulse
      - PROXMOX_NODE_1_TOKEN_SECRET=a01534f7-xxxx
      - IGNORE_SSL_ERRORS=true
      - NODE_TLS_REJECT_UNAUTHORIZED=0
      - LOG_LEVEL=debug
    restart: unless-stopped
networks: {}
```

My logs are:

```
pulse-app  | 2025-03-10 14:38:12 debug [ProxmoxClient][node-1]: Raw resource data for container 107:
pulse-app  | {
pulse-app  |   "resourceData": {
pulse-app  |     "name": "traefik",
pulse-app  |     "netout": 80451,
pulse-app  |     "maxswap": 536870912,
pulse-app  |     "status": "running",
pulse-app  |     "disk": 671744000,
pulse-app  |     "cpus": 1,
pulse-app  |     "maxmem": 536870912,
pulse-app  |     "mem": 45596672,
pulse-app  |     "diskread": 186830848,
pulse-app  |     "maxdisk": 2147483648,
pulse-app  |     "netin": 457627186,
pulse-app  |     "pid": 6263,
pulse-app  |     "ha": {
pulse-app  |       "managed": 0
pulse-app  |     },
pulse-app  |     "cpu": 0,
pulse-app  |     "tags": "community-script;proxy",
pulse-app  |     "vmid": 107,
pulse-app  |     "swap": 0,
pulse-app  |     "uptime": 499642,
pulse-app  |     "type": "lxc",
pulse-app  |     "diskwrite": 0
pulse-app  |   }
pulse-app  | }
pulse-app  | 2025-03-10 14:38:12 debug [ProxmoxClient][node-1]: API Request: GET /nodes/pve/lxc/105/status/current
pulse-app  | {}
pulse-app  | 2025-03-10 14:38:12 debug [ProxmoxClient][node-1]: API Request: GET /nodes/pve/lxc/102/status/current
pulse-app  | {}
pulse-app  | 2025-03-10 14:38:12 error [ProxmoxClient][node-1]: API Error: getaddrinfo EAI_AGAIN pve
pulse-app  | {
pulse-app  |   "error": {
pulse-app  |     "message": "getaddrinfo EAI_AGAIN pve",
pulse-app  |     "name": "Error",
pulse-app  |     "code": "EAI_AGAIN"
pulse-app  |   }
pulse-app  | }
```

As you can see, it goes well and then it doesn't.... I didn't even start the browser. This is coming out of the container. I think the number of requests is blowing(overwhelming) up the proxmox api and then proxmox starts to refuse the connections.
