### ISSUE TITLE
[BUG] Permission error on configuration save

### ISSUE THREAD

**Issue by Anexgohan** [rcourtman/Pulse#109]
running this compose:  
```
services:
  pulse-server:
    # https://github.com/rcourtman/pulse
    image: rcourtman/pulse:latest
    container_name: pulse
    env_file:
      - .env
    volumes:
      - /etc/localtime:/etc/localtime:ro  #read only local time
      - ./docker-data/pulse_config:/usr/src/app/config
    ports:
      - "17655:7655"
    restart: unless-stopped
    healthcheck:
      test:
        - CMD
        - node
        - -e
        - "const http = require('http'); const options = { hostname:
          'localhost', port: 7655, path: '/', method: 'GET' }; const
          req = http.request(options, (res) => { process.exit(res.statusCode >=
          200 && res.statusCode < 400 ? 0 : 1); }); req.on('error', () => {
          process.exit(1); }); req.end();"
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 20s
```

in the GUI, clicking on Save Button causes write permission issues:  

![Image](https://github.com/user-attachments/assets/96e39c1c-4ee1-4e4d-8023-e33b23500af2)

from docker compose logs:  
```
pulse  | [ConfigApi.writeEnvFile] Error writing file: [Error: EACCES: permission denied, open '/usr/src/app/config/.env'] {
pulse  |   errno: -13,
pulse  |   code: 'EACCES',
pulse  |   syscall: 'open',
pulse  |   path: '/usr/src/app/config/.env'
pulse  | }
pulse  | Error saving configuration: [Error: EACCES: permission denied, open '/usr/src/app/config/.env'] {
pulse  |   errno: -13,
pulse  |   code: 'EACCES',
pulse  |   syscall: 'open',
pulse  |   path: '/usr/src/app/config/.env'
pulse  | }
pulse  | [API /api/config] Error: [Error: EACCES: permission denied, open '/usr/src/app/config/.env'] {
pulse  |   errno: -13,
pulse  |   code: 'EACCES',
pulse  |   syscall: 'open',
pulse  |   path: '/usr/src/app/config/.env'
pulse  | }
```
